import type { Metadata } from "next";
import { Geist, Geist_Mono, Source_Serif_4 } from "next/font/google";
import "./globals.css";

import localFont from 'next/font/local'

const gilroy = localFont({
  src: [
    { path: '../fonts/Gilroy-Medium.woff', weight: '500' },
    { path: '../fonts/Gilroy-SemiBold.woff', weight: '600' },
  ],
  variable: '--font-gilroy',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${gilroy.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
