import type { Metadata } from "next";
import "./globals.css";

import localFont from 'next/font/local'
import { Raleway } from 'next/font/google'

const gilroy = localFont({
  src: [
    { path: '../fonts/Gilroy-Medium.woff', weight: '500' },
    { path: '../fonts/Gilroy-SemiBold.woff', weight: '600' },
  ],
  variable: '--font-gilroy',
})

const raleway = Raleway({
  subsets: ['latin'],
  variable: '--font-raleway',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${gilroy.variable} ${raleway.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
